#!/system/bin/sh
#Battery Tweaks
#To select a tweak, remove the "#" before the setting
#Optimal values for up_threshold is 45-95. Higher number=higher battery/lower performance. Lower number=higher performance/lower battery life

mount -o remount rw /system
mount -o remount rw /sys

# Start tweak by car vs driver @ xda-developers
#
# force the governor into ondemand to apply additional CPU tweaks
echo "Setting Awake Governor";
GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;

echo "Current Governor: $GOVERNOR";

if [ $GOVERNOR != "ondemand" ] 
then
	#
	# comment out the below line if you don't want to force ondemand
	# the remainder of the script will fail when another governor is set
	echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
	# this script is specific to the ondemand governor, so if you commented
	# out the line above then you will need to uncomment the below line
	#exit 1;
	sleep 1;
	GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;
	echo "Governor now set to $GOVERNOR";
fi;

#
#
# End tweak
#

#=========
#OnDemand. 
#=========
AWAKE_GOVERNOR="ondemand"
#SLEEP_GOVERNOR="ondemand"
echo "Setting up_threshold";
echo "45" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
#===================================
#0=off  1=on. Uncomment to make active.
#===================================	
	#echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias;
	#echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
	echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential;
	#echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/ignore_nice_load;
	
#===================================
#Be cautious when changing sampling_rate values as too high/low can cause lag
#===================================
	echo "50000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;

#=============================================================================
#Powersave [no additional settings required, powersave only stays at 100 MHz]
#Best Sleep Governor
#=============================================================================
echo "Setting Sleep Governor";
#SLEEP_GOVERNOR="powersave";

echo "Done"
