#!/system/bin/sh

mount -o remount rw /system

echo "  " >> /system/build.prop;
echo "#Lightning Zap! Tweaks" >> /system/build.prop;
echo "debug.composition.type=gpu" >> /system/build.prop;
echo "dalvik.vm.verify-bytecode=false" >> /system/build.prop;
echo "dalvik.vm.dexpot-data-only=1" >> /system/build.prop;
echo "persist.android.strictmode=0" >> /system/build.prop;
echo "ro.min_pointer_dur=1" >> /system/build.prop;
echo "dalvik.vm.execution-mode=int:jit" >> /system/build.prop;
echo "ro.HOME_APP_MEM=4096" >> /system/build.prop;
echo "#" >> /system/build.prop;
echo "ro.media.enc.jpeg.quality=100" >> /system/build.prop;
echo "#" >> /system/build.prop;
echo "##Save battery" >> /system/build.prop;
echo "pm.sleep_mode=1" >> /system/build.prop;
echo "ro.ril.disable.power.collapse=1" >> /system/build.prop;
echo "persist.sys.shutdown.mode=hibernate" >> /system/build.prop;
echo "#" >> /system/build.prop;
echo "##Increase overall touch responsiveness" >> /system/build.prop;
echo "debug.performance.tuning=1" >> /system/build.prop;
echo "video.accelerate.hw=1" >> /system/build.prop;
echo "#" >> /system/build.prop;
echo "##Net speed tweaks" >> /system/build.prop;
echo "net.tcp.buffersize.hsdpa=4094,87380,393216,4096,16384,110208" >> /system/build.prop;
echo "net.tcp.buffersize.default=4096,87380,256960,4096,16384,256960" >> /system/build.prop;
echo "net.tcp.buffersize.wifi=4096,87380,256960,4096,16384,256960" >> /system/build.prop;
echo "net.tcp.buffersize.umts=4096,87380,256960,4096,16384,256960" >> /system/build.prop;
echo "net.tcp.buffersize.gprs=4096,87380,256960,4096,16384,256960" >> /system/build.prop;
echo "net.tcp.buffersize.edge=4096,87380,256960,4096,16384,256960" >> /system/build.prop;

busybox sed -i 's|ro.modversion=*|ro.modversion=Lightning Zapped! |' /system/build.prop;

rm $0
